/* 
 * Copyright (C) 2015 jeqo
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jeqo.samples.eventsource.event;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClientAddedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientAddedEvent\",\"namespace\":\"com.jeqo.samples.eventsource.event\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"created\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public long created;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ClientAddedEvent() {}

  /**
   * All-args constructor.
   */
  public ClientAddedEvent(java.lang.CharSequence name, java.lang.Long created) {
    this.name = name;
    this.created = created;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return created;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: created = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'created' field.
   */
  public java.lang.Long getCreated() {
    return created;
  }

  /**
   * Sets the value of the 'created' field.
   * @param value the value to set.
   */
  public void setCreated(java.lang.Long value) {
    this.created = value;
  }

  /** Creates a new ClientAddedEvent RecordBuilder */
  public static com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder newBuilder() {
    return new com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder();
  }
  
  /** Creates a new ClientAddedEvent RecordBuilder by copying an existing Builder */
  public static com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder newBuilder(com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder other) {
    return new com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder(other);
  }
  
  /** Creates a new ClientAddedEvent RecordBuilder by copying an existing ClientAddedEvent instance */
  public static com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder newBuilder(com.jeqo.samples.eventsource.event.ClientAddedEvent other) {
    return new com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for ClientAddedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientAddedEvent>
    implements org.apache.avro.data.RecordBuilder<ClientAddedEvent> {

    private java.lang.CharSequence name;
    private long created;

    /** Creates a new Builder */
    private Builder() {
      super(com.jeqo.samples.eventsource.event.ClientAddedEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.created)) {
        this.created = data().deepCopy(fields()[1].schema(), other.created);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ClientAddedEvent instance */
    private Builder(com.jeqo.samples.eventsource.event.ClientAddedEvent other) {
            super(com.jeqo.samples.eventsource.event.ClientAddedEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.created)) {
        this.created = data().deepCopy(fields()[1].schema(), other.created);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'created' field */
    public java.lang.Long getCreated() {
      return created;
    }
    
    /** Sets the value of the 'created' field */
    public com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder setCreated(long value) {
      validate(fields()[1], value);
      this.created = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'created' field has been set */
    public boolean hasCreated() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'created' field */
    public com.jeqo.samples.eventsource.event.ClientAddedEvent.Builder clearCreated() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ClientAddedEvent build() {
      try {
        ClientAddedEvent record = new ClientAddedEvent();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.created = fieldSetFlags()[1] ? this.created : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
